// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed icon.svg
var resourceIconSvgData []byte
var resourceIconSvg = &fyne.StaticResource{
	StaticName:    "icon.svg",
	StaticContent: resourceIconSvgData,
}
