// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMissingCoreDependencies() {
  return window['go']['main']['App']['CheckMissingCoreDependencies']();
}

export function CheckPortConflicts() {
  return window['go']['main']['App']['CheckPortConflicts']();
}

export function DetectProjectPath(arg1) {
  return window['go']['main']['App']['DetectProjectPath'](arg1);
}

export function DownloadDependency(arg1) {
  return window['go']['main']['App']['DownloadDependency'](arg1);
}

export function FetchRemoteDependencies() {
  return window['go']['main']['App']['FetchRemoteDependencies']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCategoryLogs(arg1, arg2) {
  return window['go']['main']['App']['GetCategoryLogs'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDependencyConfig() {
  return window['go']['main']['App']['GetDependencyConfig']();
}

export function GetDetailedResources() {
  return window['go']['main']['App']['GetDetailedResources']();
}

export function GetScanResult() {
  return window['go']['main']['App']['GetScanResult']();
}

export function GetServicesStatus() {
  return window['go']['main']['App']['GetServicesStatus']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsMariaDBRunning() {
  return window['go']['main']['App']['IsMariaDBRunning']();
}

export function IsServiceRunning(arg1) {
  return window['go']['main']['App']['IsServiceRunning'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInHeidiSQL() {
  return window['go']['main']['App']['OpenInHeidiSQL']();
}

export function OpenProjectCaddyfile(arg1) {
  return window['go']['main']['App']['OpenProjectCaddyfile'](arg1);
}

export function QueryDatabases() {
  return window['go']['main']['App']['QueryDatabases']();
}

export function QueryTables(arg1) {
  return window['go']['main']['App']['QueryTables'](arg1);
}

export function ReloadCaddy() {
  return window['go']['main']['App']['ReloadCaddy']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanServices() {
  return window['go']['main']['App']['ScanServices']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function StartCaddy(arg1, arg2) {
  return window['go']['main']['App']['StartCaddy'](arg1, arg2);
}

export function StartMailpit(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartMailpit'](arg1, arg2, arg3, arg4, arg5);
}

export function StartMariaDB(arg1) {
  return window['go']['main']['App']['StartMariaDB'](arg1);
}

export function StartPHP(arg1) {
  return window['go']['main']['App']['StartPHP'](arg1);
}

export function StartProjectRuntime(arg1) {
  return window['go']['main']['App']['StartProjectRuntime'](arg1);
}

export function StartTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminalSession'](arg1, arg2, arg3);
}

export function StopCaddy() {
  return window['go']['main']['App']['StopCaddy']();
}

export function StopMailpit() {
  return window['go']['main']['App']['StopMailpit']();
}

export function StopMariaDB(arg1) {
  return window['go']['main']['App']['StopMariaDB'](arg1);
}

export function StopPHP(arg1) {
  return window['go']['main']['App']['StopPHP'](arg1);
}

export function StopProjectRuntime(arg1) {
  return window['go']['main']['App']['StopProjectRuntime'](arg1);
}

export function StopTerminalSession(arg1) {
  return window['go']['main']['App']['StopTerminalSession'](arg1);
}
