// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {resource} from '../models';
import {scanner} from '../models';

export function CheckMissingCoreDependencies():Promise<Record<string, boolean>>;

export function CheckPortConflicts():Promise<Record<string, boolean>>;

export function DetectProjectPath(arg1:string):Promise<main.ProjectDetectResult>;

export function DownloadDependency(arg1:string):Promise<void>;

export function FetchRemoteDependencies():Promise<config.DependencyConfig>;

export function GetAppVersion():Promise<string>;

export function GetCategoryLogs(arg1:string,arg2:string):Promise<Array<main.LogEntry>>;

export function GetConfig():Promise<config.WincmpConfig>;

export function GetDependencyConfig():Promise<config.DependencyConfig>;

export function GetDetailedResources():Promise<resource.DetailedResources>;

export function GetScanResult():Promise<scanner.ScanResult>;

export function GetServicesStatus():Promise<Record<string, boolean>>;

export function IsAdmin():Promise<boolean>;

export function IsMariaDBRunning():Promise<boolean>;

export function IsServiceRunning(arg1:string):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInHeidiSQL():Promise<void>;

export function OpenProjectCaddyfile(arg1:string):Promise<void>;

export function QueryDatabases():Promise<Array<string>>;

export function QueryTables(arg1:string):Promise<Array<string>>;

export function ReloadCaddy():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartApp():Promise<void>;

export function SaveConfig(arg1:config.WincmpConfig):Promise<void>;

export function ScanServices():Promise<scanner.ScanResult>;

export function SelectFolder():Promise<string>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartCaddy(arg1:string,arg2:string):Promise<void>;

export function StartMailpit(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function StartMariaDB(arg1:string):Promise<void>;

export function StartPHP(arg1:string):Promise<void>;

export function StartProjectRuntime(arg1:string):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StopCaddy():Promise<void>;

export function StopMailpit():Promise<void>;

export function StopMariaDB(arg1:string):Promise<void>;

export function StopPHP(arg1:string):Promise<void>;

export function StopProjectRuntime(arg1:string):Promise<void>;

export function StopTerminalSession(arg1:string):Promise<void>;
